GET http://localhost:9090/api/posts

###

POST http://localhost:9090/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}
###


POST http://localhost:9090/api/posts
Content-Type: application/json

{
"id": 0,
"content": "New Post"
}

###


POST http://localhost:9090/api/posts
Content-Type: application/json

{
  "id": 2,
  "content": "hello"
}

###

DELETE http://localhost:9090/api/posts/2

